{"id": "29465", "image_urls": ["https://prod-resize.tiendainglesa.com.uy/images/medium/P029465-1.jpg?20220705194926"], "source": "tienda_inglesa", "url": "https://www.tiendainglesa.com.uy/Tapas-para-Empanadas-Hojaldradas-TIENDA-INGLESA-20-Unidades.producto?3076,,42", "link": "https://www.tiendainglesa.com.uy/Tapas-para-Empanadas-Hojaldradas-TIENDA-INGLESA-20-Unidades.producto?3076,,42", "property_type": "WAREHOUSE", "product_name": "Tapas para Empanadas Hojaldradas TIENDA INGLESA 20 Unidades", "images": []}
{"id": "218557", "image_urls": ["https://prod-resize.tiendainglesa.com.uy/images/medium/P218557-1.jpg?20211127160027"], "source": "tienda_inglesa", "url": "https://www.tiendainglesa.com.uy/Galleta-Arroz-CEREALITAS-160-gr.producto?14185,,42", "link": "https://www.tiendainglesa.com.uy/Galleta-Arroz-CEREALITAS-160-gr.producto?14185,,42", "property_type": "WAREHOUSE", "product_name": "Galleta Arroz CEREALITAS 160 gr", "images": []}
{"id": "17491", "image_urls": ["https://prod-resize.tiendainglesa.com.uy/images/medium/P017491-1.jpg?20221010160029"], "source": "tienda_inglesa", "url": "https://www.tiendainglesa.com.uy/Zapallito-Granel-Kg-.producto?8021,,42", "link": "https://www.tiendainglesa.com.uy/Zapallito-Granel-Kg-.producto?8021,,42", "property_type": "FRESH", "product_name": "Zapallito Granel (Kg)", "images": []}
{"id": "21683", "image_urls": ["https://prod-resize.tiendainglesa.com.uy/images/medium/P021683-1.jpg?20230315144119"], "source": "tienda_inglesa", "url": "https://www.tiendainglesa.com.uy/Leche-Entera-Larga-Vida-TIENDA-INGLESA-1-L.producto?1943,,42", "link": "https://www.tiendainglesa.com.uy/Leche-Entera-Larga-Vida-TIENDA-INGLESA-1-L.producto?1943,,42", "property_type": "FRESH", "product_name": "Leche Entera Larga Vida TIENDA INGLESA 1 L", "images": []}
{"id": "29465", "image_urls": ["https://prod-resize.tiendainglesa.com.uy/images/medium/P029465-1.jpg?20220705194926"], "source": "tienda_inglesa", "url": "https://www.tiendainglesa.com.uy/Tapas-para-Empanadas-Hojaldradas-TIENDA-INGLESA-20-Unidades.producto?3076,,42", "link": "https://www.tiendainglesa.com.uy/Tapas-para-Empanadas-Hojaldradas-TIENDA-INGLESA-20-Unidades.producto?3076,,42", "property_type": "WAREHOUSE", "product_name": "Tapas para Empanadas Hojaldradas TIENDA INGLESA 20 Unidades", "images": []}
{"id": "218557", "image_urls": ["https://prod-resize.tiendainglesa.com.uy/images/medium/P218557-1.jpg?20211127160027"], "source": "tienda_inglesa", "url": "https://www.tiendainglesa.com.uy/Galleta-Arroz-CEREALITAS-160-gr.producto?14185,,42", "link": "https://www.tiendainglesa.com.uy/Galleta-Arroz-CEREALITAS-160-gr.producto?14185,,42", "property_type": "WAREHOUSE", "product_name": "Galleta Arroz CEREALITAS 160 gr", "images": []}
{"id": "17491", "image_urls": ["https://prod-resize.tiendainglesa.com.uy/images/medium/P017491-1.jpg?20221010160029"], "source": "tienda_inglesa", "url": "https://www.tiendainglesa.com.uy/Zapallito-Granel-Kg-.producto?8021,,42", "link": "https://www.tiendainglesa.com.uy/Zapallito-Granel-Kg-.producto?8021,,42", "property_type": "FRESH", "product_name": "Zapallito Granel (Kg)", "images": []}
{"id": "21683", "image_urls": ["https://prod-resize.tiendainglesa.com.uy/images/medium/P021683-1.jpg?20230315144119"], "source": "tienda_inglesa", "url": "https://www.tiendainglesa.com.uy/Leche-Entera-Larga-Vida-TIENDA-INGLESA-1-L.producto?1943,,42", "link": "https://www.tiendainglesa.com.uy/Leche-Entera-Larga-Vida-TIENDA-INGLESA-1-L.producto?1943,,42", "property_type": "FRESH", "product_name": "Leche Entera Larga Vida TIENDA INGLESA 1 L", "images": []}
{"id": "29465", "image_urls": ["https://prod-resize.tiendainglesa.com.uy/images/medium/P029465-1.jpg?20220705194926"], "source": "tienda_inglesa", "url": "https://www.tiendainglesa.com.uy/Tapas-para-Empanadas-Hojaldradas-TIENDA-INGLESA-20-Unidades.producto?3076,,42", "link": "https://www.tiendainglesa.com.uy/Tapas-para-Empanadas-Hojaldradas-TIENDA-INGLESA-20-Unidades.producto?3076,,42", "property_type": "WAREHOUSE", "product_name": "Tapas para Empanadas Hojaldradas TIENDA INGLESA 20 Unidades", "images": []}
{"id": "218557", "image_urls": ["https://prod-resize.tiendainglesa.com.uy/images/medium/P218557-1.jpg?20211127160027"], "source": "tienda_inglesa", "url": "https://www.tiendainglesa.com.uy/Galleta-Arroz-CEREALITAS-160-gr.producto?14185,,42", "link": "https://www.tiendainglesa.com.uy/Galleta-Arroz-CEREALITAS-160-gr.producto?14185,,42", "property_type": "WAREHOUSE", "product_name": "Galleta Arroz CEREALITAS 160 gr", "images": []}
{"id": "17491", "image_urls": ["https://prod-resize.tiendainglesa.com.uy/images/medium/P017491-1.jpg?20221010160029"], "source": "tienda_inglesa", "url": "https://www.tiendainglesa.com.uy/Zapallito-Granel-Kg-.producto?8021,,42", "link": "https://www.tiendainglesa.com.uy/Zapallito-Granel-Kg-.producto?8021,,42", "property_type": "FRESH", "product_name": "Zapallito Granel (Kg)", "images": []}
{"id": "21683", "image_urls": ["https://prod-resize.tiendainglesa.com.uy/images/medium/P021683-1.jpg?20230315144119"], "source": "tienda_inglesa", "url": "https://www.tiendainglesa.com.uy/Leche-Entera-Larga-Vida-TIENDA-INGLESA-1-L.producto?1943,,42", "link": "https://www.tiendainglesa.com.uy/Leche-Entera-Larga-Vida-TIENDA-INGLESA-1-L.producto?1943,,42", "property_type": "FRESH", "product_name": "Leche Entera Larga Vida TIENDA INGLESA 1 L", "images": []}
